version: "3.1"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: headless_blog
      MYSQL_USER: headless_blog
      MYSQL_PASSWORD: test123

  api:
    build:
     dockerfile: nginx/Dockerfile
     context: ./
    depends_on:
      - php-fpm

  php-fpm:
    build:
      dockerfile: laravel/Dockerfile
      context: ./
    depends_on:
      - db

